export const STORE_KEY = '@@customisation'
export const LOAD_THEME_AND_SECTION_SETTINGS = `${STORE_KEY}/LOAD_THEME_AND_SECTION_SETTINGS`
export const HOT_UPDATE_THEME_AND_SECTION_SETTINGS = `${STORE_KEY}/HOT_UPDATE_THEME_AND_SECTION_SETTINGS`
export const UPDATE_THEME_SETTINGS = `${STORE_KEY}/CHANGE_THEME_SETTINGS`
export const UPDATE_SECTIONS_SETTINGS = `${STORE_KEY}/UPDATE_SECTIONS_SETTINGS`
export const UPDATE_SECTIONS_CONTENT = `${STORE_KEY}/UPDATE_SECTIONS_CONTENT`
