export const STORE_KEY = '@@customisation'
export const LOAD_THEME_AND_SECTION_SETTINGS = `${STORE_KEY}/LOAD_THEME_AND_SECTION_SETTINGS`
export const HOT_UPDATE_THEME_AND_SECTION_SETTINGS = `${STORE_KEY}/HOT_UPDATE_THEME_AND_SECTION_SETTINGS`
